"""Agent state definition for LangGraph."""

from __future__ import annotations

from typing import Annotated, Any, TypedDict

from langgraph.graph.message import add_messages
from langchain_core.messages import BaseMessage


class ToolStep(TypedDict, total=False):
    """A single step in the agent's execution plan."""

    tool_name: str
    tool_args: dict[str, Any]
    result: str | None
    error: str | None


class AgentState(TypedDict):
    """State shared across all LangGraph nodes.

    Attributes:
        messages: Full conversation history (managed by LangGraph add_messages reducer).
        user_query: The raw user question.
        intent: Classified intent category (retrieval / generation / review / general / test_generation / verification).
        plan: Ordered list of tool-call steps generated by the Planner.
        current_step: Index into plan (which step is currently being executed).
        tool_results: Accumulated results from all executed tool calls.
        final_answer: The final synthesized response.
        iteration_count: Number of executor loops (safety limit).
        review_results: Accumulated review results (for test_generation intent).
        repair_count: Number of repair attempts so far (max 3, for test_generation intent).
        verification_report: JSON-serializable VerificationReport dict (for verification intent).
    """

    messages: Annotated[list[BaseMessage], add_messages]
    user_query: str
    intent: str
    plan: list[dict[str, Any]]
    current_step: int
    tool_results: list[dict[str, Any]]
    final_answer: str
    iteration_count: int
    review_results: list[dict[str, Any]]
    repair_count: int
    verification_report: dict[str, Any]
